### ISSUE TITLE
Surat Keluar Manual tidak Teragendakan

### ISSUE THREAD

**Issue by dirr** [budirs86/aplikasi_tndev5#22]
Pada saat Proses Pembuatan Surat Keluar Manual dari Menu : Agenda Surat -> Surat Keluar Manual , setelah seluruh field diisi sampai langkah terkahir dan surat dikirim, Surat tersebut tidak teragendakan di Menu Agenda Surat Keluar

**Comment by budirs86** [comment]
![screen shot 2015-12-14 at 12 56 01 pm](https://cloud.githubusercontent.com/assets/1733247/11773872/23421bca-a262-11e5-839e-2f5e01e24dd5.png)

**Comment by dirr** [comment]
Ternyata krn ada duplikasi TU berada di instansi induk
