### ISSUE TITLE
Struktur Jabatan pada saat Edit Pengguna tidak semua muncul

### ISSUE THREAD

**Issue by dirr** [budirs86/aplikasi_tndev5#23]
Proses terjadi pada saat melakukan edit pengguna melalui menu struktur pengguna:
- DIbuat di Instansi Demo --> Sekretaris Daerah
- user: dirga, kewenangan: admin_unit 
  -Tampilan Sturuktur Jabatan di Instansi Demo --> Sekretariat Daerah
  ![screen shot 2015-12-14 at 11 48 56 am](https://cloud.githubusercontent.com/assets/8622097/11773174/b5696062-a258-11e5-9e36-02620e291f6f.png)

-Pada saat tambah pengguna baru, seluruh jabatan yang di buat ada
![Uploading Screen Shot 2015-12-14 at 11.40.27 AM.png…]()

-Tetapi pada saat edit pengguna mau memindahkan user ke jabatan yang lain, sesuai tampilan tidak muncul jabatan 
![screen shot 2015-12-14 at 11 40 56 am](https://cloud.githubusercontent.com/assets/8622097/11773196/f0093710-a258-11e5-8e0f-d8ec9bb26fd8.png)

**Comment by budirs86** [comment]
sudah diperbaiki

**Comment by dirr** [comment]
Oke Pak. Terimakasih
