### ISSUE TITLE
History Disposisi tidak kelihatan semua

### ISSUE THREAD

**Issue by dirr** [budirs86/aplikasi_tndev5#25]
Untuk history disposisi yang kelihatan hanya dari pendisposisi pertama, jika disposisi berjenjang 
misal : surat masuk (Kadis) > Penerima Dispo Kadis (Sekdis) > Penerima Dispo Sekdis (Kabag) > Penerima Dispo Kabag (Kasi), Kasi hanya dapat membaca isi disposisi dari Kadis saja utk history disposisi sekdis, kabag tidak terbaca oleh kasi
![screen shot 2015-12-16 at 9 47 30 am](https://cloud.githubusercontent.com/assets/8622097/11830716/29e6a26a-a3da-11e5-9d20-de9310c3e48c.png)

**Comment by budirs86** [comment]
Sudah diperbaiki yah....untuk disposisi masing-masing sudah sesuai dengan pesan dispo dari atasannya..
