### ISSUE TITLE
Desain untuk box tujuan surat kurang user friendly

### ISSUE THREAD

**Issue by simaya** [budirs86/aplikasi_tndev5#32]
redesign ulang tampilan untuk tujuan surat baik surat keluar maupun surat masuk, bisa adopsi tampilan email.

**Comment by budirs86** [comment]
on progress

**Comment by budirs86** [comment]
![screen shot 2015-12-22 at 9 55 10 am](https://cloud.githubusercontent.com/assets/1733247/11946902/317eec6e-a892-11e5-8e88-a47a5619f404.png)
