### ISSUE TITLE
Kolom komentar jika di isi, akan ada pop up cek kesalahan lagi

### ISSUE THREAD

**Issue by simaya** [budirs86/aplikasi_tndev5#4]
Login sebagai staf kasubbag >> menu surat keluar >> buat surat

![screen shot 2015-12-08 at 11 48 26 am](https://cloud.githubusercontent.com/assets/8026127/11647939/be61c608-9da0-11e5-8330-27fdddd1979b.png)

**Comment by budirs86** [comment]
sudah ok
