### ISSUE TITLE
Pemeriksa surat

### ISSUE THREAD

**Issue by simaya** [budirs86/aplikasi_tndev5#5]
Pembuat surat : staf
pemeriksa : kasubbag, kabag, asisten, sekda dan bupati
event : setelah kasubbag periksa surat yang datang dari staf, surat tidak da di konsep pemeriksa. 
Revisi  : harusnya masih ada arsip yang ada di konsep pemeriksa untuk mengetahui progress surat yang sedang dia periksa beserta perubahannya

**Comment by budirs86** [comment]
sudah di patch
